main: me.infinityz.SurvivalUniverse
name: Survival-Unviverse
version: 2020.3.3-RC.01-A
api-version: 1.13
author: InfinityZ25
commands:
  pvp:
  chunk:
  city:
  home:
  t:
    usage: "\u00A7cCommand usage: /<command> <Player> <x> <y> <z> [world]"
  randomtp:
    usage: "\u00A7cCommand usage: /<command> <Player>"
  admin:
  helper:
  ally:
    usage: "\u00A7cCommand usage: /<command> <add:list:remove> [Player]"